gogs:
  image: "gogs/gogs:0.7.33"
  container_name: "gogs"
  ports:
    - "10022:22"
    - "10080:3000"
  volumes:
    - "./data/gogs:/data"
    - "./entrypoint.sh:/entrypoint.sh"
  links:
    - "postgresql:postgresql"
  entrypoint: "/entrypoint.sh"
postgresql:
  image: "sameersbn/postgresql:9.4-8"
  container_name: "gogs-postgresql"
  volumes:
    - "./data/postgresql:/var/lib/postgresql"
  environment:
    - "DB_USER=gogs"
    - "DB_PASS=changethis123"
    - "DB_NAME=gogs"
