gogs:
  image: "gogs/gogs:0.7.33"
  container_name: "gogs"
  ports:
    - "22:22"
  volumes:
    - "./data/gogs:/data"
  links:
    - "gogs-postgresql:postgresql"
postgresql:
  image: "infoslack/alpine-postgres"
  container_name: "gogs-postgresql"
  volumes:
    - "./data/postgresql:/var/lib/postgresql"
